#!/usr/bin/env python3
"""Convert the remaining Mario-Level-1 runtime frames for PGOS.

The reference project keeps these frames as hard-coded sprite-sheet rectangles
inside its Pygame classes. This converter mirrors those rectangles once at
build time so the firmware only contains immutable RGB565+A8 data.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image


FRAME_SPECS = (
    ("mario_skid", "mario_bros.png", 130, 32, 14, 16),
    ("mario_death", "mario_bros.png", 160, 32, 15, 16),
    ("mario_flag1", "mario_bros.png", 194, 32, 12, 16),
    ("mario_flag2", "mario_bros.png", 210, 33, 12, 16),
    ("mario_big_skid", "mario_bros.png", 128, 0, 16, 32),
    ("mario_big_crouch", "mario_bros.png", 160, 10, 16, 22),
    ("mario_big_flag1", "mario_bros.png", 193, 2, 16, 30),
    ("mario_big_flag2", "mario_bros.png", 209, 2, 16, 29),
    ("mario_fire_idle", "mario_bros.png", 176, 48, 16, 32),
    ("mario_fire_run1", "mario_bros.png", 81, 48, 16, 32),
    ("mario_fire_run2", "mario_bros.png", 97, 48, 15, 32),
    ("mario_fire_run3", "mario_bros.png", 113, 48, 15, 32),
    ("mario_fire_jump", "mario_bros.png", 144, 48, 16, 32),
    ("mario_fire_skid", "mario_bros.png", 128, 48, 16, 32),
    ("mario_fire_crouch", "mario_bros.png", 160, 58, 16, 22),
    ("mario_fire_throw", "mario_bros.png", 336, 48, 16, 32),
    ("koopa_shell", "smb_enemies_sheet.png", 360, 5, 16, 15),
    ("one_up", "item_objects.png", 16, 0, 16, 16),
    ("fire_flower_1", "item_objects.png", 0, 32, 16, 16),
    ("fire_flower_2", "item_objects.png", 16, 32, 16, 16),
    ("fire_flower_3", "item_objects.png", 32, 32, 16, 16),
    ("fire_flower_4", "item_objects.png", 48, 32, 16, 16),
    ("star_1", "item_objects.png", 1, 48, 15, 16),
    ("star_2", "item_objects.png", 17, 48, 15, 16),
    ("star_3", "item_objects.png", 33, 48, 15, 16),
    ("star_4", "item_objects.png", 49, 48, 15, 16),
    ("brick_piece", "item_objects.png", 68, 20, 8, 8),
    ("pole_flag", "item_objects.png", 128, 32, 16, 16),
    ("castle_flag", "item_objects.png", 129, 2, 14, 14),
    ("fireball_1", "item_objects.png", 96, 144, 8, 8),
    ("fireball_2", "item_objects.png", 104, 144, 8, 8),
    ("fireball_3", "item_objects.png", 96, 152, 8, 8),
    ("fireball_4", "item_objects.png", 104, 152, 8, 8),
    ("fireball_explode1", "item_objects.png", 112, 144, 16, 16),
    ("fireball_explode2", "item_objects.png", 112, 160, 16, 16),
    ("fireball_explode3", "item_objects.png", 112, 176, 16, 16),
)


def safe_name(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red * 31 // 255) << 11) | ((green * 63 // 255) << 5) | (
        blue * 31 // 255
    )


def emit(values: list[int], value_type: str, per_line: int) -> str:
    lines = []
    for offset in range(0, len(values), per_line):
        chunk = values[offset : offset + per_line]
        if value_type == "uint16_t":
            values_text = ", ".join(f"0x{value:04X}" for value in chunk)
        else:
            values_text = ", ".join(str(value) for value in chunk)
        lines.append("    " + values_text)
    return ",\n".join(lines)


def generate(source_root: Path, output: Path) -> None:
    graphics = source_root / "resources" / "graphics"
    lines = [
        "// Generated by tools/convert_mario_extra_assets.py; do not edit by hand.",
        "#pragma once",
        "",
        "#include <cstdint>",
        '#include "ui/PixelSprite.h"',
        "",
        "namespace pgos::platformer_extra_assets {",
        "",
        "using Frame = pgos::PixelSprite;",
        "",
    ]
    names = []
    for name, sheet_name, x, y, width, height in FRAME_SPECS:
        with Image.open(graphics / sheet_name) as sheet:
            frame = sheet.convert("RGBA").crop((x, y, x + width, y + height))
        pixels = []
        alpha = []
        pixel_data = getattr(frame, "get_flattened_data", frame.getdata)()
        for red, green, blue, source_alpha in pixel_data:
            pixels.append(rgb565(red, green, blue))
            alpha.append(
                0 if source_alpha == 0 or (red, green, blue) == (0, 0, 0)
                else source_alpha
            )
        packed = []
        for pixel in pixels:
            packed.extend((pixel & 0xFF, (pixel >> 8) & 0xFF))
        packed.extend(alpha)
        symbol = safe_name(name)
        names.append(symbol)
        lines.extend(
            [
                f"inline constexpr uint8_t {symbol}_image_data[] = {{",
                emit(packed, "uint8_t", 24),
                "};",
                f"inline constexpr Frame {symbol} = {{",
                f'    "{name}", {width}, {height},',
                f"    {symbol}_image_data, sizeof({symbol}_image_data), false",
                "};",
                "",
            ]
        )
    lines.append("inline constexpr const Frame* all[] = {")
    lines.extend(f"    &{name}," for name in names)
    lines.extend(["};", "", "}  // namespace pgos::platformer_extra_assets", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(names)} frames -> {output}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    generate(args.source.resolve(), args.output.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
