"""Convert Mario-Level-1's precomposed level strip to RGB565 chunks."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


CHUNK_WIDTH = 320


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red * 31 // 255) << 11) | ((green * 63 // 255) << 5) | (
        blue * 31 // 255
    )


def emit_bytes(values: list[int]) -> str:
    lines = []
    for offset in range(0, len(values), 16):
        chunk = values[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk))
    return ",\n".join(lines)


def generate(source: Path, output: Path, chunk_width: int = CHUNK_WIDTH) -> int:
    if chunk_width <= 0:
        raise ValueError("chunk_width must be positive")

    with Image.open(source) as source_image:
        image = source_image.convert("RGB")
    frames = []
    for left in range(0, image.width, chunk_width):
        crop = image.crop(
            (left, 0, min(left + chunk_width, image.width), image.height)
        )
        data = []
        get_flattened_data = getattr(crop, "get_flattened_data", None)
        pixel_data = (
            get_flattened_data() if get_flattened_data is not None else crop.getdata()
        )
        for red, green, blue in pixel_data:
            value = rgb565(red, green, blue)
            data.extend((value & 0xFF, (value >> 8) & 0xFF))
        name = f"level_{left // chunk_width}"
        frames.append((name, crop.width, crop.height, data))

    lines = [
        "// Generated by tools/convert_mario_level_background.py; do not edit by hand.",
        "#pragma once",
        "#include <cstdint>",
        '#include "ui/PixelSprite.h"',
        "",
        "namespace pgos::platformer_original_assets {",
    ]
    for name, width, height, data in frames:
        lines.extend(
            [
                f"inline constexpr uint8_t {name}_image_data[] = {{",
                emit_bytes(data),
                "};",
                f"inline constexpr pgos::PixelSprite {name} = {{",
                f'    "{name}", {width}, {height},',
                f"    {name}_image_data, sizeof({name}_image_data), true",
                "};",
                "",
            ]
        )
    lines.append("}  // namespace pgos::platformer_original_assets")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(frames)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert a precomposed Mario level strip to RGB565 chunks"
    )
    parser.add_argument("--source", type=Path, required=True,
                        help="source level_1.png")
    parser.add_argument("--output", type=Path, required=True,
                        help="generated C++ header")
    parser.add_argument("--chunk-width", type=int, default=CHUNK_WIDTH)
    args = parser.parse_args()
    count = generate(args.source.resolve(), args.output.resolve(), args.chunk_width)
    print(f"generated {count} background chunks -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
