"""Generate compact LVGL A8 menu icons from the pinned Lucide font."""

from __future__ import annotations

import io
import re
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


LUCIDE_VERSION = "0.468.0"
ICON_SIZE = 24
FONT_SIZE = 21
ICONS = (
    "gamepad-2",
    "settings-2",
    "wrench",
    "monitor",
    "volume-2",
    "lightbulb",
    "bluetooth",
    "wifi",
    "radio-tower",
    "gauge",
    "clock-3",
    "palette",
    "cherry",
    "blocks",
    "brick-wall",
    "spade",
)


def download(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read()


def glyph_codepoint(css: str, name: str) -> int:
    match = re.search(
        rf'\.icon-{re.escape(name)}:before\s*\{{\s*content:\s*"\\([0-9a-f]+)"',
        css,
    )
    if match is None:
        raise RuntimeError(f"Lucide glyph not found: {name}")
    return int(match.group(1), 16)


def render_icon(font: ImageFont.FreeTypeFont, codepoint: int) -> bytes:
    image = Image.new("L", (ICON_SIZE, ICON_SIZE), 0)
    draw = ImageDraw.Draw(image)
    glyph = chr(codepoint)
    left, top, right, bottom = draw.textbbox((0, 0), glyph, font=font)
    x = (ICON_SIZE - (right - left)) // 2 - left
    y = (ICON_SIZE - (bottom - top)) // 2 - top
    draw.text((x, y), glyph, font=font, fill=255)
    return image.tobytes()


def identifier(name: str) -> str:
    return name.upper().replace("-", "_")


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16])
        rows.append(f"    {chunk},")
    return "\n".join(rows)


def main() -> None:
    base = f"https://unpkg.com/lucide-static@{LUCIDE_VERSION}/font/"
    css = download(base + "lucide.css").decode("utf-8")
    font = ImageFont.truetype(io.BytesIO(download(base + "Lucide.ttf")), FONT_SIZE)

    output = [
        "// Generated by tools/generate_ui_icons.py. Do not edit by hand.",
        f"// Lucide Static {LUCIDE_VERSION}, ISC License.",
        "",
    ]
    for name in ICONS:
        symbol = identifier(name)
        data = render_icon(font, glyph_codepoint(css, name))
        output.extend(
            (
                f"static const uint8_t ICON_{symbol}_DATA[] = {{",
                format_bytes(data),
                "};",
                f"static const lv_image_dsc_t ICON_{symbol} = {{",
                "    {LV_IMAGE_HEADER_MAGIC, LV_COLOR_FORMAT_A8, 0,",
                f"     {ICON_SIZE}, {ICON_SIZE}, {ICON_SIZE}, 0}},",
                f"    sizeof(ICON_{symbol}_DATA), ICON_{symbol}_DATA, nullptr, nullptr,",
                "};",
                "",
            )
        )

    destination = Path(__file__).resolve().parents[1] / "src" / "ui" / "UiIconData.inc"
    destination.write_text("\n".join(output), encoding="ascii")
    print(f"wrote {destination} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
