#!/usr/bin/env python3
"""Generate the TinyLM story font from the Chinese training corpus."""

from __future__ import annotations

import argparse
from pathlib import Path

import pyarrow.parquet as pq

import generate_bitmap_font as bitmap_font


EXTRA_CHARACTERS = "".join(chr(value) for value in range(0x20, 0x7F)) + "�"


def collect_dataset_characters(paths: list[Path]) -> set[str]:
    characters: set[str] = set(EXTRA_CHARACTERS)
    for path in paths:
        parquet = pq.ParquetFile(path)
        for batch in parquet.iter_batches(columns=["text"], batch_size=8192):
            for text in batch.column(0).to_pylist():
                if not text:
                    continue
                characters.update(
                    character
                    for character in text
                    if character.isprintable() and not character.isspace()
                )
    return characters


def array_text(
    characters: list[str],
    rendered: dict[int, tuple[int, bytes]],
) -> str:
    lines = ["const TinyLmBitmapGlyph TINYLM_FONT_GLYPHS[] PROGMEM = {"]
    for character in characters:
        advance, bitmap = rendered[ord(character)]
        values = ", ".join(f"0x{value:02X}" for value in bitmap)
        lines.append(
            f"    {{0x{ord(character):04X}, {advance}, {{{values}}}}},"
        )
    lines.append("};")
    return "\n".join(lines)


def generate(parquets: list[Path], bdf_path: Path, output_path: Path) -> bool:
    requested = collect_dataset_characters(parquets)
    ascent, glyphs = bitmap_font.parse_bdf(bdf_path)
    supported = sorted(
        (character for character in requested if ord(character) in glyphs),
        key=ord,
    )
    missing = sorted(
        (character for character in requested if ord(character) not in glyphs),
        key=ord,
    )
    rendered = {
        ord(character): bitmap_font.render_bdf_glyph(
            glyphs[ord(character)], ascent
        )
        for character in supported
    }
    content = """// Generated by tools/generate_tinylm_font.py.
// Character set: all printable non-whitespace characters in TinyStories-Zh-1M.
// Font: Fusion Pixel Font 12px proportional zh_hans (OFL-1.1).
#pragma once

#include <Arduino.h>
#include <stddef.h>
#include <stdint.h>

struct TinyLmBitmapGlyph {
    uint32_t codepoint;
    uint8_t advance;
    uint8_t bitmap[40];
};

"""
    content += array_text(supported, rendered)
    content += (
        "\n\nconstexpr size_t TINYLM_FONT_GLYPH_COUNT = "
        "sizeof(TINYLM_FONT_GLYPHS) / sizeof(TINYLM_FONT_GLYPHS[0]);\n"
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists() and output_path.read_text(encoding="utf-8") == content:
        print(f"TinyLM font already current: {output_path}")
        return False
    output_path.write_text(content, encoding="utf-8", newline="\n")
    print(
        f"generated TinyLM font: {len(supported)} glyphs, "
        f"{len(missing)} unsupported dataset characters"
    )
    if missing:
        details = " ".join(f"U+{ord(value):04X}" for value in missing)
        print(f"TinyLM unsupported characters: {details}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--parquet", type=Path, nargs="+", required=True)
    parser.add_argument("--bdf", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    generate(args.parquet, args.bdf, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
